environment:
  matrix:
    - PYTHON: "C:\\Miniconda35"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Miniconda36"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Miniconda35-x64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Miniconda36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"

install:
  - "%PYTHON%\\scripts\\conda.exe config --set always_yes true"
  - "%PYTHON%\\scripts\\conda.exe install numpy pytest"
  - "%PYTHON%\\scripts\\conda.exe install -c conda-forge pytest-cov"

build: off

test_script:
  - "%PYTHON%\\python.exe -m pytest --cov=mmappickle --cov-report=term-missing"

artifacts:
  - path: dist\*
